[tool.poetry]
name = "itly-plugin-snowplow"
version = "0.1.3"
description = "Iteratively Analytics SDK - Snowplow Plugin"
readme="README.md"
authors = ["Iteratively"]
license = "MIT"
packages = [
    { include = "itly_plugin_snowplow" }
]

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
secondary = true

[tool.poetry.dependencies]
python = "^3.6"
snowplow-tracker = "^0.8.3"
itly-sdk = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pytest-httpserver = "^0.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
