[tool.poetry]
name = "itly.plugin-segment"
version = "0.1.5"
description = "Iteratively Analytics SDK - Segment Plugin"
readme="README.md"
authors = ["Iteratively"]
license = "MIT"
packages = [
    { include = "itly" }
]

[tool.poetry.dependencies]
python = "^3.6"
analytics-python = "^1.2.9"
"itly.sdk" = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pytest-httpserver = "^0.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
