[tool.poetry]
name = "itly-plugin-amplitude"
version = "0.1.14"
description = "Iteratively Analytics SDK - Amplitude Plugin"
readme="README.md"
authors = ["Iteratively"]
license = "MIT"
packages = [
    { include = "itly_plugin_amplitude" }
]

[[tool.poetry.source]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
secondary = true

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.24.0"
itly-sdk = "^0.1.23"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
